package com.altnative.Alt.Native.Enum;

public enum DisputeStatus {
    DISPUTE_REQUEST_PENDING_REVIEW,
    //by administrator only
    DISPUTE_REQUEST_ACCEPTED,
    DISPUTE_REQUEST_REJECTED,
//    DISPUTE_REQUEST_PENDING_ADMIN_REVIEW,
    DISPUTE_REQUEST_REFUND_PENDING,
    DISPUTE_REQUEST_COMPLETED,
    DISPUTE_REQUEST_ACCEPT_COMPLETED,
    REFUND_FAILED
}
