package com.altnative.Alt.Native.Enum;

public enum MilestoneEnum {
    ORDER_STARTED,
    ADD_ON_OFFER_MADE,
    ADD_ON_OFFER_DECLINED,
    ADD_ON_ORDER_STARTED, //equivalent to add_on_offer_accepted
    ARRANGE_FOR_COURIER,
//    MATERIAL_LOCATION_PENDING,
//    LOCATION_REGISTERED,
    COURIER_OTW,
    COURIER_DELIVERED,
    MEASUREMENTS_REQUESTED,
    PAYMENT,
    PROGRESS_UPDATE_REQUEST,
    PROGRESS_UPDATE,
    FINAL_APPROVAL_OK,
    FINAL_APPROVAL_REJECTED,
    FINAL_APPROVAL_PENDING,
    ADD_ON_ORDER_COMPLETE,
    ORDER_COMPLETE,
    DISPUTE_REQUEST_PENDING_REVIEW,
    DISPUTE_REQUEST_PENDING_ADMIN_REVIEW, //by administrator only
//    DISPUTE_REQUEST_REFUND_PENDING,
    DISPUTE_REQUEST_COMPLETED,
    DISPUTE_REQUEST_ACCEPTED,
    DISPUTE_REQUEST_FAILED_REFUND,
    JNT_STATUS,
    SWAP_DELIVERY_PAID
}
